[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "my_whatsapp_group_analytics"
version = "0.0.1"
description = "Analysis of chat group data of whatsapp."
authors = [
  { name = "Patricia Quiroz" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.14.0"


[tool.ruff]
line-length = 99
src = ["my_whatsapp_group_analytics"]
include = ["pyproject.toml", "my_whatsapp_group_analytics/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["my_whatsapp_group_analytics"]
force-sort-within-sections = true

